#!/usr/bin/env python

import sys
from shuttle import Network

try:
    addr = sys.argv[1]
except Exception:
    print "usage: get_history <dogecoin_address>"
    sys.exit(1)

n = Network()
n.start(wait=True)
h = n.synchronous_get([ ('blockchain.address.get_history',[addr]) ])[0]
for item in h:
    print item['tx_hash'], item['height']

