#!/usr/bin/env python

import time, shuttle

shuttle.set_verbosity(False)     # default is True
network = shuttle.Network({'auto_cycle':True})
network.register_callback('peers',lambda: shuttle.print_json(network.irc_servers.keys()))

if not network.start(wait=True):
    print "Not connected"
    exit(1)

print "Connected to", network.interface.server
while not network.irc_servers:
    time.sleep(1)


